In [1]:
import pandas as pd

atp_2000 = pd.read_excel("atp_2000.xls")

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

atp_2000.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,Loser,WRank,LRank,W1,L1,W2,L2,W3,L3,W4,L4,W5,L5,Wsets,Lsets,Comment
0,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,63,77,6.0,4.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
1,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Enqvist T.,Clement A.,5,56,6.0,3.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
2,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,40,655,6.0,7.0,7.0,5.0,6.0,3.0,NaN,NaN,NaN,NaN,2,1,Completed
3,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Federer R.,Knippschild J.,65,87,6.0,1.0,6.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
4,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,81,198,7.0,6.0,5.0,7.0,6.0,4.0,NaN,NaN,NaN,NaN,2,1,Completed

In [4]:
atp_2000.describe()

,ATP,Best of,W1,L1,W2,L2,W3,L3,W4,L4,W5,L5,Wsets,Lsets
count,2963.000000,2963.000000,2949.000000,2949.000000,2929.000000,2929.000000,1368.000000,1368.000000,267.000000,267.000000,92.000000,92.000000,2963.000000,2963.000000
mean,34.573405,3.353021,5.786707,4.056968,5.730966,3.805736,6.000000,3.570175,5.779026,3.838951,6.717391,3.793478,2.133986,0.411070
std,18.783485,0.762636,1.224307,1.811170,1.295748,1.866119,0.940824,1.753096,1.277278,1.897837,2.071927,2.731735,0.457442,0.551628
min,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,20.000000,3.000000,6.000000,3.000000,6.000000,2.000000,6.000000,2.000000,6.000000,2.000000,6.000000,2.000000,2.000000,0.000000
50%,34.000000,3.000000,6.000000,4.000000,6.000000,4.000000,6.000000,4.000000,6.000000,4.000000,6.000000,3.000000,2.000000,0.000000
75%,50.500000,3.000000,6.000000,6.000000,6.000000,6.000000,6.000000,5.000000,6.000000,6.000000,7.000000,5.250000,2.000000,1.000000
max,69.000000,5.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,20.000000,18.000000,3.000000,2.000000

In [11]:
Dosedel = atp_2000[(atp_2000["Winner"] == "Dosedel S.") | (atp_2000["Loser"] == "Dosedel S.")]

In [13]:
len(Dosedel[Dosedel["Winner"] == "Dosedel S."])

17

In [14]:
len(Dosedel[Dosedel["Loser"] == "Dosedel S."])

20

In [15]:
max(Dosedel[Dosedel["Loser"] == "Dosedel S."]["LRank"])

70

In [16]:
min((Dosedel[Dosedel["Loser"] == "Dosedel S."]["LRank"]))

50

In [17]:
Dosedel.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,Loser,WRank,LRank,W1,L1,W2,L2,W3,L3,W4,L4,W5,L5,Wsets,Lsets,Comment
0,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,63,77,6.0,4.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
17,1,Adelaide,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,2nd Round,3,Escude N.,Dosedel S.,40,63,7.0,6.0,6.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
128,5,Sydney,Sydney International,2000-01-10,International,Outdoor,Hard,1st Round,3,Dosedel S.,Woodforde M.,69,128,6.0,3.0,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
141,5,Sydney,Sydney International,2000-01-10,International,Outdoor,Hard,2nd Round,3,Dosedel S.,Ilie A.,69,47,6.0,3.0,7.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,2,0,Completed
148,5,Sydney,Sydney International,2000-01-10,International,Outdoor,Hard,Quarterfinals,3,Corretja A.,Dosedel S.,28,69,3.0,6.0,7.0,5.0,6.0,3.0,NaN,NaN,NaN,NaN,2,1,Completed